"""Crear tabla categoria y producto_categoria

Revision ID: 6812bf867f82
Revises: 9eeceafb6d00
Create Date: 2026-05-07 13:47:43.825762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6812bf867f82'
down_revision: Union[str, None] = '9eeceafb6d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_categoria_categoria_id'), 'producto_categoria', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_producto_categoria_producto_id'), 'producto_categoria', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producto_categoria_producto_id'), table_name='producto_categoria')
    op.drop_index(op.f('ix_producto_categoria_categoria_id'), table_name='producto_categoria')
    op.drop_table('producto_categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###