"""Agrega campos de fecha_creacion, fecha_ultima_modificacion, usuario_ultima_modificacion para auditoria

Revision ID: 78b19231223c
Revises: b79078a38642
Create Date: 2026-05-08 19:14:35.936343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78b19231223c'
down_revision: Union[str, None] = 'b79078a38642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria', sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
    op.add_column('categoria', sa.Column('fecha_ultima_modificacion', sa.DateTime(), nullable=True))
    op.add_column('categoria', sa.Column('usuario_ultima_modificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('producto', sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
    op.add_column('producto', sa.Column('fecha_ultima_modificacion', sa.DateTime(), nullable=True))
    op.add_column('producto', sa.Column('usuario_ultima_modificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'usuario_ultima_modificacion')
    op.drop_column('producto', 'fecha_ultima_modificacion')
    op.drop_column('producto', 'fecha_creacion')
    op.drop_column('categoria', 'usuario_ultima_modificacion')
    op.drop_column('categoria', 'fecha_ultima_modificacion')
    op.drop_column('categoria', 'fecha_creacion')
    # ### end Alembic commands ###