"""Agregamos categoría y producto_categoria

Revision ID: 9eeceafb6d00
Revises: cd064be2d448
Create Date: 2026-05-07 13:33:30.801180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9eeceafb6d00"
down_revision: Union[str, None] = "cd064be2d448"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "producto",
        sa.Column("descripcion", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("producto", sa.Column("precio_base", sa.Float(), nullable=False))
    op.add_column("producto", sa.Column("imagen_url", sa.JSON(), nullable=True))
    op.add_column("producto", sa.Column("disponible", sa.Boolean(), nullable=False))
    op.drop_column("producto", "stock")
    op.drop_column("producto", "stock_minimo")
    op.drop_column("producto", "categoria")
    op.drop_column("producto", "precio")
    op.drop_column("producto", "activo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "producto",
        sa.Column("activo", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "producto",
        sa.Column(
            "precio",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "producto",
        sa.Column("categoria", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "producto",
        sa.Column("stock_minimo", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "producto",
        sa.Column("stock", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("producto", "disponible")
    op.drop_column("producto", "imagen_url")
    op.drop_column("producto", "precio_base")
    op.drop_column("producto", "descripcion")
    # ### end Alembic commands ###
